name: infinite_tab_button
description: Package for making beautiful infinite tab button. You can use only button for making MaterialTab look alike behaviour.
version: 0.0.1-beta
author: Farhan Yuda Pahlevi<pahlevi.kun@gmail.com>
homepage: https://github.com/pahlevikun/Infinite-Tab-Button.git

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.10.15-pre.148 <2.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter